name: Commit checks
on: push
jobs:
  validate:
    name: Validate source.yaml
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Validate
      run: python tools/validate.py source.yaml
